// MY NSDA Constants & Default Seed Data

export const COLORS = {
  primaryRed: '#E3060B',
  redDark: '#C20408',
  teal: '#008F8F',
  tealDark: '#007C7C',
  white: '#FFFFFF',
  background: '#F7F9FC',
  border: '#E0E6EF',
  text: '#111827',
  subtext: '#94A3B8',
  softRed: '#FFF0F0',
  softTeal: '#EFFAFA',
  green: '#10B981', // For active/online indicators only
};

export const INITIAL_SPECIALTIES = [
  { id: 'spec-1', name: 'All Doctors', slug: 'all' },
  { id: 'spec-2', name: 'Orthopaedic', slug: 'orthopaedic', icon: 'Bone' },
  { id: 'spec-3', name: 'Surgeon', slug: 'surgeon', icon: 'Scissors' },
  { id: 'spec-4', name: 'Physician', slug: 'physician', icon: 'Stethoscope' },
  { id: 'spec-5', name: 'Cardiologist', slug: 'cardiologist', icon: 'Heart' },
  { id: 'spec-6', name: 'Dermatologist', slug: 'dermatologist', icon: 'Sparkles' },
  { id: 'spec-7', name: 'Pediatrician', slug: 'pediatrician', icon: 'Baby' },
  { id: 'spec-8', name: 'Neurologist', slug: 'neurologist', icon: 'Activity' },
  { id: 'spec-9', name: 'Gynecologist', slug: 'gynecologist', icon: 'UserCheck' },
  { id: 'spec-10', name: 'Ophthalmologist', slug: 'ophthalmologist', icon: 'Eye' },
  { id: 'spec-11', name: 'Dentist', slug: 'dentist', icon: 'Smile' },
];

export const INITIAL_CITIES = [
  { id: 'city-1', name: 'All Cities', state: '' },
  { id: 'city-2', name: 'Mumbai', state: 'Maharashtra' },
  { id: 'city-3', name: 'Delhi', state: 'Delhi' },
  { id: 'city-4', name: 'Bangalore', state: 'Karnataka' },
  { id: 'city-5', name: 'Hyderabad', state: 'Telangana' },
  { id: 'city-6', name: 'Chennai', state: 'Tamil Nadu' },
  { id: 'city-7', name: 'Kolkata', state: 'West Bengal' },
  { id: 'city-8', name: 'Pune', state: 'Maharashtra' },
  { id: 'city-9', name: 'Ahmedabad', state: 'Gujarat' },
  { id: 'city-10', name: 'Jaipur', state: 'Rajasthan' },
];

export const INITIAL_DOCTORS = [
  {
    id: 'doc-1',
    user_id: 'user-doc-1',
    full_name: 'Dr. Rajesh Sharma',
    email: 'dr.sharma@nsda.org.in',
    phone: '+91 98201 44552',
    avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, MS (Orthopaedics), MCh',
    specialty_id: 'spec-2',
    specialty_name: 'Orthopaedic',
    subspecialty: 'Joint Replacement & Spine Surgery',
    registration_number: 'MMC-2004/08/3120',
    hospital: 'Lilavati Hospital & Research Centre',
    clinic_address: 'Suite 402, Medical Enclave, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    experience_years: 18,
    bio: 'Senior Consultant Orthopaedic Surgeon with 18+ years of dedicated surgical experience. Specializes in robotic-assisted knee and hip arthroplasty, complex trauma reconstruction, and minimally invasive spine interventions.',
    consultation_fee: '₹1,500',
    available_timings: 'Mon - Fri: 10:00 AM - 2:00 PM, 5:00 PM - 8:00 PM',
    verification_status: 'verified',
    verification_reason: null,
    verified_at: '2025-01-10T10:00:00Z',
    is_featured: true,
    is_online: true,
    phone_visible: true,
    email_visible: true,
    rating: 4.9,
    reviews_count: 142,
    created_at: '2025-01-01T08:00:00Z',
  },
  {
    id: 'doc-2',
    user_id: 'user-doc-2',
    full_name: 'Dr. Priya Venkatraman',
    email: 'dr.priya.v@nsda.org.in',
    phone: '+91 98452 77819',
    avatar_url: 'https://images.unsplash.com/photo-1594824813576-90f707f433aa?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, MD (General Medicine), DNB',
    specialty_id: 'spec-4',
    specialty_name: 'Physician',
    subspecialty: 'Diabetology & Metabolic Care',
    registration_number: 'KMC-2010/12/9904',
    hospital: 'Manipal Hospitals',
    clinic_address: 'Ground Floor, Old Airport Road',
    city: 'Bangalore',
    state: 'Karnataka',
    experience_years: 14,
    bio: 'Compassionate Consultant Physician focusing on preventative lifestyle medicine, glycemic control, hypertension protocols, and geriatric internal medicine.',
    consultation_fee: '₹1,200',
    available_timings: 'Mon - Sat: 9:00 AM - 1:00 PM',
    verification_status: 'verified',
    verification_reason: null,
    verified_at: '2025-01-12T14:30:00Z',
    is_featured: true,
    is_online: true,
    phone_visible: true,
    email_visible: false,
    rating: 4.8,
    reviews_count: 98,
    created_at: '2025-01-03T11:20:00Z',
  },
  {
    id: 'doc-3',
    user_id: 'user-doc-3',
    full_name: 'Dr. Amitav Banerjee',
    email: 'dr.amitav.b@nsda.org.in',
    phone: '+91 98300 23118',
    avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, MS (General Surgery), FMAS, FIAGES',
    specialty_id: 'spec-3',
    specialty_name: 'Surgeon',
    subspecialty: 'Advanced Laparoscopic & GI Surgery',
    registration_number: 'WBMC-2008/04/5512',
    hospital: 'Apollo Gleneagles Hospitals',
    clinic_address: '58 Canal Circular Road, Kankurgachi',
    city: 'Kolkata',
    state: 'West Bengal',
    experience_years: 16,
    bio: 'Fellowship trained Laparoscopic & Gastrointestinal Surgeon pioneering single-incision abdominal laparoscopic procedures and complex hernia repairs.',
    consultation_fee: '₹1,800',
    available_timings: 'Tue, Thu, Sat: 4:00 PM - 8:00 PM',
    verification_status: 'verified',
    verification_reason: null,
    verified_at: '2025-01-15T09:15:00Z',
    is_featured: true,
    is_online: false,
    phone_visible: true,
    email_visible: true,
    rating: 4.9,
    reviews_count: 210,
    created_at: '2025-01-05T09:00:00Z',
  },
  {
    id: 'doc-4',
    user_id: 'user-doc-4',
    full_name: 'Dr. Sunita Deshmukh',
    email: 'dr.sunita.d@nsda.org.in',
    phone: '+91 97660 88214',
    avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    specialty_id: 'spec-6',
    specialty_name: 'Dermatologist',
    subspecialty: 'Clinical Dermatology & Aesthetic Laser',
    registration_number: 'MMC-2012/03/1842',
    hospital: 'Ruby Hall Clinic',
    clinic_address: 'Plot 40, Sassoon Road, Sangamvadi',
    city: 'Pune',
    state: 'Maharashtra',
    experience_years: 12,
    bio: 'Expert dermatologist addressing chronic dermatoses, pediatric skin conditions, trichology treatments, and modern cosmetic laser therapies.',
    consultation_fee: '₹1,000',
    available_timings: 'Mon - Fri: 11:00 AM - 5:00 PM',
    verification_status: 'verified',
    verification_reason: null,
    verified_at: '2025-01-18T16:00:00Z',
    is_featured: true,
    is_online: true,
    phone_visible: true,
    email_visible: true,
    rating: 4.7,
    reviews_count: 85,
    created_at: '2025-01-08T12:00:00Z',
  },
  {
    id: 'doc-5',
    user_id: 'user-doc-5',
    full_name: 'Dr. Vikramaditya Rathore',
    email: 'dr.rathore@nsda.org.in',
    phone: '+91 99820 11993',
    avatar_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, MD (Medicine), DM (Cardiology), FACC',
    specialty_id: 'spec-5',
    specialty_name: 'Cardiologist',
    subspecialty: 'Interventional Cardiology',
    registration_number: 'DMC-2002/09/2019',
    hospital: 'Fortis Escorts Heart Institute',
    clinic_address: 'Okhla Road, Sukhdev Vihar',
    city: 'Delhi',
    state: 'Delhi',
    experience_years: 22,
    bio: 'Internationally recognized Senior Interventional Cardiologist. Completed over 5,000 coronary angioplasties, complex bifurcation stenting, and TAVR procedures.',
    consultation_fee: '₹2,500',
    available_timings: 'Mon - Sat: 10:00 AM - 4:00 PM',
    verification_status: 'verified',
    verification_reason: null,
    verified_at: '2025-01-20T10:00:00Z',
    is_featured: true,
    is_online: true,
    phone_visible: true,
    email_visible: true,
    rating: 5.0,
    reviews_count: 320,
    created_at: '2025-01-09T07:30:00Z',
  },
  {
    id: 'doc-6',
    user_id: 'user-doc-6',
    full_name: 'Dr. Ananya Sen',
    email: 'dr.ananya.s@nsda.org.in',
    phone: '+91 98110 56420',
    avatar_url: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, MD (Pediatrics), Fellowship Neonatology',
    specialty_id: 'spec-7',
    specialty_name: 'Pediatrician',
    subspecialty: 'Neonatal Critical Care & Child Development',
    registration_number: 'DMC-2015/07/8819',
    hospital: 'Max Super Speciality Hospital',
    clinic_address: '1, 2, Press Enclave Road, Saket',
    city: 'Delhi',
    state: 'Delhi',
    experience_years: 10,
    bio: 'Dedicated pediatrician with special focus on newborn intensive care, immunization schedules, childhood nutrition, and developmental milestones.',
    consultation_fee: '₹1,200',
    available_timings: 'Mon - Fri: 9:30 AM - 2:00 PM',
    verification_status: 'verified',
    verification_reason: null,
    verified_at: '2025-02-01T12:00:00Z',
    is_featured: false,
    is_online: false,
    phone_visible: false,
    email_visible: true,
    rating: 4.8,
    reviews_count: 64,
    created_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'doc-7',
    user_id: 'user-doc-7',
    full_name: 'Dr. Sanjay Kulkarni',
    email: 'dr.sanjay.k@nsda.org.in',
    phone: '+91 98220 90123',
    avatar_url: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, MS (Orthopaedics)',
    specialty_id: 'spec-2',
    specialty_name: 'Orthopaedic',
    subspecialty: 'Sports Injury & Arthroscopy',
    registration_number: 'MMC-2018/06/4410',
    hospital: 'Sancheti Institute for Orthopaedics',
    clinic_address: '16 Shivaji Nagar',
    city: 'Pune',
    state: 'Maharashtra',
    experience_years: 7,
    bio: 'Sports medicine specialist focusing on ACL reconstructions, shoulder rotator cuff repair, and modern athletic rehabilitation.',
    consultation_fee: '₹1,100',
    available_timings: 'Mon - Sat: 11:00 AM - 4:00 PM',
    verification_status: 'pending',
    verification_reason: null,
    verified_at: null,
    is_featured: false,
    is_online: true,
    phone_visible: true,
    email_visible: true,
    rating: 4.6,
    reviews_count: 22,
    created_at: '2025-02-10T11:00:00Z',
  },
  {
    id: 'doc-8',
    user_id: 'user-doc-8',
    full_name: 'Dr. Meera Nambiar',
    email: 'dr.meera.n@nsda.org.in',
    phone: '+91 94470 33812',
    avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
    qualifications: 'MBBS, DGO, MS (Obstetrics & Gynaecology)',
    specialty_id: 'spec-9',
    specialty_name: 'Gynecologist',
    subspecialty: 'High-risk Pregnancy & Fetal Medicine',
    registration_number: 'TCMC-2011/04/7201',
    hospital: 'Aster Medcity',
    clinic_address: 'Kuttisahib Road, Cheranalloor',
    city: 'Hyderabad',
    state: 'Telangana',
    experience_years: 15,
    bio: 'Consultant Obstetrician and Gynecologist known for high-risk maternal care, laparoscopic hysteroscopy, and comprehensive adolescent reproductive health.',
    consultation_fee: '₹1,400',
    available_timings: 'Mon - Fri: 10:00 AM - 3:00 PM',
    verification_status: 'verified',
    verification_reason: null,
    verified_at: '2025-01-25T09:00:00Z',
    is_featured: false,
    is_online: true,
    phone_visible: true,
    email_visible: true,
    rating: 4.9,
    reviews_count: 178,
    created_at: '2025-01-20T08:00:00Z',
  }
];

export const DEFAULT_APP_SETTINGS = {
  about_nsda: {
    title: 'About National Society for Doctors Association (NSDA)',
    description: 'NSDA is the premier nationwide professional medical association dedicated to empowering doctors, facilitating clinical collaboration, providing state-of-the-art medical networking, and giving patients and peer professionals verified access to trusted doctors across India.',
    founded_year: '1998',
    total_members: '12,500+ Verified Doctors',
    email: 'contact@nsda.org.in',
    phone: '+91 22 2847 9000',
    address: 'NSDA Bhavan, Medical Enclave, Central Avenue, New Delhi - 110001, India',
    mission: 'To uphold highest standards of medical ethics, professional solidarity, continuous medical education, and patient welfare.',
    presidents_message: 'Welcome to MY NSDA. Together we form a stronger medical community connected professionally and socially.'
  },
  terms_privacy: {
    terms: 'By accessing and utilizing the MY NSDA Doctors Directory, all users and members agree to adhere to Indian Medical Council professional conduct ethics, respect physician privacy, and use listed information solely for authentic clinical referral or consultation purposes. Any unauthorized scraping, data harvesting, or unsolicited commercial marketing will lead to immediate legal prosecution.',
    privacy: 'We prioritize doctor confidentiality. Each doctor has independent autonomy over the public display of their personal phone number and email address. Identification and medical council registration certificates are stored under strict encrypted storage, examined solely by authorized NSDA credentialing moderators.',
    last_updated: 'January 2026'
  },
  help_support: {
    support_email: 'support@nsda.org.in',
    emergency_helpline: '+91 1800 200 4567',
    whatsapp_support: '+91 98200 12345',
    operating_hours: 'Monday to Saturday: 9:00 AM - 7:00 PM IST',
    emergency_notice: 'For urgent medical emergencies, please dial 108 or visit your nearest hospital emergency room directly.',
    faq: [
      {
        q: 'How does an NSDA Doctor get verified?',
        a: 'Submit your State Medical Council (SMC) or National Medical Commission (NMC) registration certificate during or after registration. Our verification committee verifies it within 24-48 business hours.'
      },
      {
        q: 'Can I control who sees my personal phone number and email?',
        a: 'Yes! From your Doctor Dashboard under Privacy Controls, you can toggle public visibility of your phone and email at any time.'
      },
      {
        q: 'How do I report an inaccurate or impersonated doctor profile?',
        a: 'Click on the "Report Profile" button on any doctor profile card or details page, select the reason, and our Admin Moderation Board will immediately investigate.'
      },
      {
        q: 'Who can access the Admin and Super Admin dashboards?',
        a: 'Only authorized NSDA credentialing officers and platform administrators can access these portals with role-based security.'
      }
    ]
  },
  security: {
    title: 'Data Security & Doctor Privacy',
    encryption: '256-bit SSL/TLS Transport Layer Security across all data endpoints.',
    rls: 'Row Level Security enforced at database level to prevent unauthorized profile modifications.',
    compliance: 'Compliant with Indian IT Act 2000 and Telemedicine Practice Guidelines.'
  }
};
